# Generated by Django 5.1.4 on 2025-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Bebidas', 'Bebidas'), ('Hogar', 'Hogar'), ('Transporte', 'Transporte'), ('Salud', 'Salud'), ('Entretenimiento', 'Entretenimiento'), ('Otros', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(choices=[('Salario', 'Salario'), ('Negocios', 'Negocios'), ('Inversiones', 'Inversiones'), ('Regalos', 'Regalos'), ('Otros', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
