# Generated by Django 5.1.4 on 2025-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Alimentos', 'Alimentos'), ('Bebidas', 'Bebidas'), ('Hogar', 'Hogar'), ('Transporte', 'Transporte'), ('Salud', 'Salud'), ('Entretenimiento', 'Entretenimiento'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fuente',
            field=models.CharField(choices=[('Salario', 'Salario'), ('Negocios', 'Negocios'), ('Inversiones', 'Inversiones'), ('Regalos', 'Regalos'), ('Otros', 'Otros')], max_length=50),
        ),
    ]
